" set MYVIMRC path
let $MYVIMRC="~/.vim/.vimrc"

set nocompatible

" Enable the mouse
set mouse=a

" highlight while typing in search box
set incsearch

" highlight while searching
set hlsearch

" hybrid numbers
set nu rnu

" Use visual bell, instead of beeping when doing something wrong
" set visualbell

" This should unhighlight searches, after done searching
nnoremap <silent> <C-l> :nohl<CR><C-l>
