" set MYVIMRC path
let $MYVIMRC="~/.vim/.vimrc"

set nocompatible

" Enable the mouse
set mouse=a

" highlight while typing in search box
set incsearch

" highlight while searching
set hlsearch

" hybrid numbers
set nu rnu

" Use visual bell, instead of beeping when doing something wrong
" set visualbell

" This should unhighlight searches, after done searching
nnoremap <silent> <C-l> :nohl<CR><C-l>

" WSL yank support
let s:clip = '/mnt/c/Windows/System32/clip.exe'  " change this path according to your mount point
if executable(s:clip)
    augroup WSLYank
        autocmd!
        autocmd TextYankPost * if v:event.operator ==# 'y' | call system(s:clip, @0) | endif
    augroup END
endif
